# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_proxtv_internal', [dirname(__file__)])
        except ImportError:
            import _proxtv_internal
            return _proxtv_internal
        if fp is not None:
            try:
                _mod = imp.load_module('_proxtv_internal', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _proxtv_internal = swig_import_helper()
    del swig_import_helper
else:
    import _proxtv_internal
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _proxtv_internal.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _proxtv_internal.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _proxtv_internal.doubleArray___getitem__(self, *args)
    def __setitem__(self, *args): return _proxtv_internal.doubleArray___setitem__(self, *args)
    def cast(self): return _proxtv_internal.doubleArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _proxtv_internal.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_proxtv_internal.doubleArray_frompointer)
doubleArray_swigregister = _proxtv_internal.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args):
  return _proxtv_internal.doubleArray_frompointer(*args)
doubleArray_frompointer = _proxtv_internal.doubleArray_frompointer


def tv1d(*args):
  return _proxtv_internal.tv1d(*args)
tv1d = _proxtv_internal.tv1d

def tv1dw(*args):
  return _proxtv_internal.tv1dw(*args)
tv1dw = _proxtv_internal.tv1dw
# This file is compatible with both classic and new-style classes.


